### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by ShyamPraveenSingh** [muskankhedia/gsoc-organisation-analysis#2]
Hi @muskankhedia mam, 

First of all congratulations on making such a helpful project for helping students to select organizations for GSOC.

But, on your youtube video you have only showed us how to use it and there is no mention about getting started with it. If you could kindly update the README file and add the guide to installation as well it would be of great help.
Thanks again.

**Comment by muskankhedia** [comment]
Hi @ShyamPraveenSingh, Thanks for raising up the issue. I will surely update the README file soon. Further, in order to use it, you can look for the hosted server at [https://clever-shockley-78287b.netlify.app/#/](https://clever-shockley-78287b.netlify.app/#/).

**Comment by ShyamPraveenSingh** [comment]
Sure thanks a lot.

Can I make the improvements in the README file?
I just want to make my contributions and help you.

**Comment by muskankhedia** [comment]
Sure. All the contributions are most welcome.

**Comment by ShyamPraveenSingh** [comment]
I'll get right into it!!
